on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 20
    - run: sbt test
